// <auto-generated />
using System;
using JogoJustoDotNet.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JogoJustoDotNet.Migrations
{
    [DbContext(typeof(JogoDbContext))]
    partial class JogoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogoJustoDotNet.Models.DepartamentoModel", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("GerenteId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDepartamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.DesenvolvimentoModel", b =>
                {
                    b.Property<int>("IdDesenvolvimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDesenvolvimento"));

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistroDeDados")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DuracaoHoras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeTreinamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Orgao")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("StatusRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treinamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDesenvolvimento");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("DesenvolvimentoModel");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.EmpresaModel", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.EsgLogModel", b =>
                {
                    b.Property<int>("IdEsgLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEsgLog"));

                    b.Property<string>("AcaoRealizada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentoIdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEsgLog");

                    b.HasIndex("DepartamentoIdDepartamento");

                    b.ToTable("EsgLogModel");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.FuncionarioModel", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionarioId"));

                    b.Property<string>("CargaHoraria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("DataContratacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentoIdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoCargaHoraria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MentorFuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("StPcd")
                        .HasColumnType("bit");

                    b.Property<string>("TipoPcd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FuncionarioId");

                    b.HasIndex("DepartamentoIdDepartamento");

                    b.HasIndex("MentorFuncionarioId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.MetaEsgModel", b =>
                {
                    b.Property<int>("IdMetaEsg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetaEsg"));

                    b.Property<DateTime>("AtualizacaoDados")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoMetaEsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrazoMetaEsg")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoMetaEsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorAtualMetaEsg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorReferenciaMetaEsg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMetaEsg");

                    b.HasIndex("EmpresaId");

                    b.ToTable("MetaEsg");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.TokensModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tokem");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.DepartamentoModel", b =>
                {
                    b.HasOne("JogoJustoDotNet.Models.EmpresaModel", "Empresa")
                        .WithMany("Departamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.DesenvolvimentoModel", b =>
                {
                    b.HasOne("JogoJustoDotNet.Models.FuncionarioModel", "Funcionario")
                        .WithMany("Desenvolvimentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.EsgLogModel", b =>
                {
                    b.HasOne("JogoJustoDotNet.Models.DepartamentoModel", "Departamento")
                        .WithMany("EsgLogs")
                        .HasForeignKey("DepartamentoIdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.FuncionarioModel", b =>
                {
                    b.HasOne("JogoJustoDotNet.Models.DepartamentoModel", "Departamento")
                        .WithMany("Funcionarios")
                        .HasForeignKey("DepartamentoIdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JogoJustoDotNet.Models.FuncionarioModel", "Mentor")
                        .WithMany("Mentorados")
                        .HasForeignKey("MentorFuncionarioId");

                    b.Navigation("Departamento");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.MetaEsgModel", b =>
                {
                    b.HasOne("JogoJustoDotNet.Models.EmpresaModel", "Empresa")
                        .WithMany("MetasEsg")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.DepartamentoModel", b =>
                {
                    b.Navigation("EsgLogs");

                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.EmpresaModel", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("MetasEsg");
                });

            modelBuilder.Entity("JogoJustoDotNet.Models.FuncionarioModel", b =>
                {
                    b.Navigation("Desenvolvimentos");

                    b.Navigation("Mentorados");
                });
#pragma warning restore 612, 618
        }
    }
}
